NTCL/Controllers/ActivityInfoBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTCL.Controllers
{
    public class ActivityInfoBoardController : Controller
    {
        // GET: ActivityInfoBoard
        public ActionResult Index()
        {
            return View();
        }
    }
}

NTCL/Controllers/ActivityInfoDeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTCL.Controllers
{
    public class ActivityInfoDeviceController : Controller
    {
        // GET: ActivityInfoDevice
        public ActionResult Index()
        {
            return View();
        }
    }
}

NTCL/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTCL.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

NTCL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTCL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NTCL/Controllers/InfoBox/StickyNoteMessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTCL.Controllers.InfoBox
{
    public class StickyNoteMessageController : Controller
    {
        // GET: StickyNoteMessage
        public ActionResult Index()
        {
            return View();
        }
    }
}

NTCL/Controllers/InfoBoxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTCL.Controllers
{
    public class InfoBoxController : Controller
    {
        // GET: InfoBox
        public ActionResult Index()
        {
            return View();
        }
    }
}

NTCL/Controllers/MultimediaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTCL.Controllers
{
    public class MultimediaController : Controller
    {
        // GET: Multimedia
        public ActionResult Index()
        {
            return View();
        }

        //活動看版控制

        //推播裝置控制
    }
}

NTCL/Controllers/PostCastDeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTCL.Controllers
{
    public class PostCastDeviceController : Controller
    {
        // GET: PostCastDevice
        public ActionResult Index()
        {
            return View();
        }
    }
}

NTCL/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTCL.Controllers
{
    public class StatisticsController : Controller
    {
        // GET: Statistics
        public ActionResult Index()
        {
            return View();
        }
    }
}

NTCL/Views/ActivityInfoBoard/Index.cshtml
@Styles.Render("~/Content/datespickercss")
@section scripts{
    <script src="~/Scripts/jquery-ui-1.11.1.js"></script>
    <script src="~/Scripts/MultiDatesPicker v1.6.3/jquery-ui.multidatespicker.js"></script>
    <script type="text/javascript">
        var today = new Date();
        var y = today.getFullYear();
        $('#full-year').multiDatesPicker({
            addDates: ['10/14/' + y, '02/19/' + y, '01/14/' + y, '11/16/' + y],
            numberOfMonths: [3, 4],
            defaultDate: '1/1/' + y
        });

        $(function() {
            $('.btn-danger').click(function() {
                var dates = getdate();
                $.each(dates, function (i, val) {
                    console.log(val);
                });
                
            });
        });

        function getdate()
        {
            var dates = $('#simpliest-usage').multiDatesPicker('getDates');
            return dates;
        }

    </script>
    
    
}

<h2>活動資訊看版</h2><hr />

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    <li class="active"><a href="#PlayList" role="tab" data-toggle="tab">輪播資訊列表</a></li>
    <li><a href="#Declaration" role="tab" data-toggle="tab">開館公告設定 </a></li>
    <li><a href="#ScrollingText" role="tab" data-toggle="tab">跑馬燈文字設定</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div class="tab-pane active" id="PlayList">
        <div class="container">
            <div class="row col-md-12 custyle">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-5 pull-right">
                            <div class="input-group">
                                <a href="#" class="btn btn-primary btn-sm "><b>+</b> Add new </a>
                                <div class="input-group-btn search-panel">
                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                        <span id="search_concept">Filter by</span> <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">帳號</a></li>
                                        <li><a href="#">姓名</a></li>
                                        <li><a href="#">e-mail</a></li>
                                        <li class="divider"></li>
                                        <li><a href="#">Anything</a></li>
                                    </ul>
                                </div>
                                <input type="hidden" name="search_param" value="all" id="search_param">
                                <input type="text" class="form-control" name="x" placeholder="Search term...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span></button>
                                </span>
                            </div>

                        </div>
                    </div>
                </div>
                <table class="table table-striped custab">
                    <thead>
                        <tr>
                            <th>海報圖</th>
                            <th>名稱</th>
                            <th>類別</th>
                            <th>展示時間</th>
                            <th>播放比重</th>
                            <th>啟用狀態</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tr>
                        <td><img src="#" alt="Alternate Text" /></td>
                        <td>海報1</td>
                        <td>活動</td>
                        <td>永久</td>
                        <td>1</td>
                        <td>V</td>
                        <td class="text-center"><a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
                    </tr>
                    <tr>
                        <td><img src="#" alt="Alternate Text" /></td>
                        <td>海報2</td>
                        <td>活動</td>
                        <td>永久</td>
                        <td>1</td>
                        <td>V</td>
                        <td class="text-center"><a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
                    </tr>
                    <tr>
                        <td><img src="#" alt="Alternate Text" /></td>
                        <td>海報3</td>
                        <td>活動</td>
                        <td>永久</td>
                        <td>1</td>
                        <td>V</td>
                        <td class="text-center"><a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="tab-pane" id="Declaration">
        <div class="container">
            <br /><br />
            <form class="form-inline" role="form">
                <div>
                    <label class="col-sm-2 control-label" >今日開館(@(DateTime.Now.ToShortDateString()))</label>&emsp;
                    @Html.RadioButton("今日開館", true, true) 是
                    @Html.RadioButton("今日開館", false, false) 否
                </div>
                <br /><br />
                <div>
                    <label class="col-sm-2 control-label">本月休館日</label>
                    <p>Date: <div id="full-year"></div></p>
                </div>
                <br /><br />
                <a href="#" class="btn btn-danger btn-sm "><b>.</b> Save </a>
            </form>
        </div>
    </div>
        <div class="tab-pane" id="ScrollingText">
            <div class="container">
                <br /><br />
                <form class="form-horizontal" role="form">
                    <fieldset>

                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="card-holder-name">跑馬燈文字</label>
                            <div class="col-sm-10">
                                @Html.TextArea("name", "臺北市立圖書館景美分館特別於9月28日及10月5日下午1時30分至4時30分安排了「扶桑花女孩」及「放牛班的春天」兩部與教育有關的影片，並邀請專業影評人劉英台老師進行導賞解說。歡迎大手牽小手，一起來欣賞這兩部動人的影片，同時也讓我們為辛勞的教師致上最高的敬意。凡親子共同參加者，即贈送小禮物1份。更多詳細資訊歡迎查詢臺北市立圖書館網頁"
                            , new { @class = "form-control", placeholder = "文字設定", rows = 16, cols = 15 })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <button type="button" class="btn btn-success">Update</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>

NTCL/Views/ActivityInfoDevice/Index.cshtml
@{
    ViewBag.Title = "ActivityBoardList";
}

<h2>活動看板設定</h2><hr />

<div class="container">
    <div class="row col-md-12 ">
        <div class="container">
            <div class="row">
                <div class="col-xs-5 pull-right">
                    <div class="input-group">
                        <a href="#" class="btn btn-primary btn-sm "><b>+</b> Add new </a>
                        <div class="input-group-btn search-panel">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                <span id="search_concept">Filter by</span> <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">帳號</a></li>
                                <li><a href="#">姓名</a></li>
                                <li><a href="#">e-mail</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Anything</a></li>
                            </ul>
                        </div>
                        <input type="hidden" name="search_param" value="all" id="search_param">
                        <input type="text" class="form-control" name="x" placeholder="Search term...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span></button>
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <table class="table table-striped custab">

            <thead>
                <tr>
                    <th>看板編號</th>
                    <th>IP位置</th>
                    <th>啟用狀態</th>
                    <th>更新日期</th>
                    <th>更新看版</th>
                    <th class="text-center">狀態</th>
                </tr>
            </thead>
            <tr>
                <td>1</td>
                <td>192.108.1.1</td>
                <td>V</td>
                <td>2014/10/01</td>
                <td><button class="btn btn-xs">更新看版</button></td>
                <td class="text-center"><a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
            </tr>
            <tr>
                <td>2</td>
                <td>192.108.1.2</td>
                <td>V</td>
                <td>2014/10/01</td>
                <td><button class="btn btn-xs">更新看版</button></td>
                <td class="text-center"><a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
            </tr>
            <tr>
                <td>3</td>
                <td>192.108.1.3</td>
                <td>V</td>
                <td>2014/10/01</td>
                <td><button class="btn btn-xs">更新看版</button></td>
                <td class="text-center"><a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
            </tr>
        </table>
    </div>
</div>

NTCL/Views/Admin/Index.cshtml
<h2>管理員列表</h2><hr />

<div class="container">
    <div class="row col-md-12 custyle">
        <table class="table table-striped custab">
            <thead>
                <a href="#" class="btn btn-primary btn-xs pull-right"><b>+</b> Add new </a>
                <tr>
                    <th>ID</th>
                    <th>帳號</th>
                    <th>資訊</th>
                    <th class="text-center">狀態</th>
                </tr>
            </thead>
            <tr>
                <td>1</td>
                <td>admin</td>
                <td>News Cate</td>
                <td class="text-center"><a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
            </tr>
            <tr>
                <td>2</td>
                <td>admin2</td>
                <td>Main Products</td>
                <td class="text-center"><a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
            </tr>
            <tr>
                <td>3</td>
                <td>admin3</td>
                <td>Parent Blogs</td>
                <td class="text-center"><a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
            </tr>
        </table>
    </div>
</div>

NTCL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NTCL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NTCL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<style type="text/css">
    .footertext {
        font-size: small;
    }
</style>

<div class="jumbotron">
    <div class="container well">
        <h2><center>新北市圖書館後台</center></h2>
    </div>
    <div id="footer">
        <div class="container">
            <div class="row">
                <br>
                <div class="col-md-4">
                    <center>
                        <img src="http://oi60.tinypic.com/w8lycl.jpg" class="img-circle" alt="the-brains">
                        <br>
                        <h4 class="footertext">歷史</h4>
                        <p class="footertext">西元1923年11月設立海山郡圖書館（後改為板橋圖書館），這是臺北縣立圖書館的前身。<br>
                    </center>
                </div>
                <div class="col-md-4">
                    <center>
                        <img src="http://oi60.tinypic.com/2z7enpc.jpg" class="img-circle" alt="...">
                        <br>
                        <h4 class="footertext">轉型</h4>
                        <p class="footertext">為配合政府推動十二項重大建設及教育部「建立縣市文化中心計畫」遂於民國六十八年成立「臺北縣立文化中心籌備處」，積極選定地點，並由高而潘建築師規劃設計。<br>
                    </center>
                </div>
                <div class="col-md-4">
                    <center>
                        <img src="http://oi61.tinypic.com/307n6ux.jpg" class="img-circle" alt="...">
                        <br>
                        <h4 class="footertext">蛻變</h4>
                        <p class="footertext">臺北縣圖書資訊服務邁向新紀元，並將以『專業、人性、豐富』作為服務所有讀者之新願景而努力。<br>
                    </center>
                </div>
            </div>
            <div class="row">
                <p><center><a href="#">Contact Us</a> <p class="footertext">Copyright 2014</p></center></p>
            </div>
        </div>
    </div>
</div>

NTCL/Views/PostCastDevice/Index.cshtml
@{
    ViewBag.Title = "DeviceList";
}



<h2>輪播裝置設定</h2><hr />

<div class="container">
    <div class="row col-md-12 custyle">
        <div class="container">
            <div class="row">
                <div class="col-xs-5 pull-right">
                    <div class="input-group">
                        <a href="#" class="btn btn-primary btn-sm "><b>+</b> Add new </a>
                        <div class="input-group-btn search-panel">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                <span id="search_concept">Filter by</span> <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">帳號</a></li>
                                <li><a href="#">姓名</a></li>
                                <li><a href="#">e-mail</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Anything</a></li>
                            </ul>
                        </div>
                        <input type="hidden" name="search_param" value="all" id="search_param">
                        <input type="text" class="form-control" name="x" placeholder="Search term...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span></button>
                        </span>
                    </div>

                </div>
            </div>
        </div>

        <table class="table table-striped custab">

            <thead>
                <tr>
                    <th>裝置編號</th>
                    <th>IP位置</th>
                    <th>啟用資訊方塊</th>
                    <th>啟用狀態</th>
                    <th>更新日期</th>
                    <th>更新看版</th>
                    <th class="text-center">狀態</th>
                </tr>
            </thead>
            <tr>
                <td>1</td>
                <td>192.108.1.1</td>
                <td>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-film"></span></a>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-pencil"></span></a>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-th-large"></span></a>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-search"></span></a>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-signal"></span></a>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-off"></span></a>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-film"></span></a>
                </td>
                <td>V</td>
                <td>2014/10/01</td>
                <td><button class="btn btn-xs">更新裝置</button></td>
                <td class="text-center"><a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
            </tr>
            <tr>
                <td>2</td>
                <td>192.108.1.2</td>
                <td>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-film"></span></a>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-pencil"></span></a>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-th-large"></span></a>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-search"></span></a>

                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-film"></span></a>
                </td>
                <td>V</td>
                <td>2014/10/01</td>
                <td><button class="btn btn-xs">更新裝置</button></td>
                <td class="text-center"><a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
            </tr>
            <tr>
                <td>3</td>
                <td>192.108.1.3</td>
                <td>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-film"></span></a>

                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-th-large"></span></a>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-search"></span></a>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-signal"></span></a>
                    <a href="#" class="btn btn-xs btn-info"><span class="glyphicon glyphicon-off"></span></a>
                </td>
                <td>V</td>
                <td>2014/10/01</td>
                <td><button class="btn btn-xs">更新裝置</button></td>
                <td class="text-center"><a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
            </tr>
        </table>
    </div>
</div>

NTCL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 新北市圖</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Multi_level_dropdown_menu.css" rel="stylesheet" />
    <style type="text/css">
        .custab {
            border: 1px solid #ccc;
            padding: 1px;
            margin: 1% 0;
            box-shadow: 3px 3px 2px #ccc;
            transition: 0.5s;
        }

            .custab:hover {
                box-shadow: 3px 3px 0px transparent;
                transition: 0.5s;
            }
    </style>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NTCL", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_Menu")
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 新北市圖系統後台</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NTCL/Views/Shared/_Menu.cshtml
<ul class="nav navbar-nav ">
    <li><a href="@Url.Action("Index", "Statistics")"><span class="glyphicon glyphicon-book"></span> 統計</a></li>
    <li><a href="@Url.Action("Index", "Admin")"><span class="glyphicon glyphicon-home"></span> 管理員列表</a></li>
    <li>
        <a id="dLabel" role="button" data-toggle="dropdown" class="btn" data-target="#" href="@Url.Action("Index", "Multimedia")">
            <span class="glyphicon glyphicon-th-list"></span> 多媒體管理系統 <span class="caret"></span>
        </a>
        <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
            <li><a href="@Url.Action("Index", "ActivityInfoDevice")">活動看版控制</a></li>
            <li class="divider"></li>
            <li><a href="@Url.Action("Index", "PostCastDevice")">推播裝置控制</a></li>
        </ul>
    </li>
    <li>
    <li><a href="@Url.Action("Index", "ActivityInfoBoard")"><span class="glyphicon glyphicon-th-list"></span> 活動資訊看板</a></li>
    <li>
        <a id="dLabel" role="button" data-toggle="dropdown" class="btn" data-target="#" href="@Url.Action("Index", "InfoBox")">
            <span class="glyphicon glyphicon-th-list"></span> 資訊方塊 <span class="caret"></span>
        </a>
        <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
            <li><a href="#">新到館藏</a></li>
            <li class="divider"></li>
            <li><a href="#">活動訊息推播</a></li>
            <li class="divider"></li>
            <li><a href="#">貴賓留影</a></li>
            <li class="divider"></li>
            <li><a href="#">愛心捐贈芳名錄</a></li>
            <li class="divider"></li>
            <li><a href="#">好書推薦大頭拍</a></li>
            <li class="divider"></li>
            <li><a href="@Url.Action("Index", "StickyNoteMessage")">便利貼留言板</a></li>
            <li class="divider"></li>
            <li><a href="#">無版權創作素材庫(CC)</a></li>
            <li class="divider"></li>
            <li><a href="#">讀者好書書評共建</a></li>
            <li class="divider"></li>
            <li><a href="#">滿意度調查</a></li>
            <li class="divider"></li>
            <li><a href="#">投票系統</a></li>
            <li class="divider"></li>
            <li class="dropdown-submenu">
                <a tabindex="-1" href="#">Hover me for more options</a>
                <ul class="dropdown-menu">
                    <li><a tabindex="-1" href="#">Second level</a></li>
                    <li><a href="#">Second level</a></li>
                    <li><a href="#">Second level</a></li>
                </ul>
            </li>
        </ul>
    </li>
</ul>